---
title: "count how many significant models in topmed"
author: "Ryan Schubert"
date: "December 3, 2020"
output: html_document
---

```{r setup, include=FALSE}
library(RSQLite)
library(tidyr)
library(dplyr)
library(stringr)
"%&%" = function(a,b) paste(a,b,sep="")
```

## get model counts for each set

```{r cars}
pop_list<-c("CAU","CHN","AFA","HIS","ALL")
model_counts_list<-list(rep(NA,5))
for (pop in 1:length(pop_list)){
  files<-list.files("Z:/data/TOPMED_Proteome/" %&% pop_list[pop] %&% "/PCAIR_modeling/06Elastic_net/dbs_out/",pattern="rho0.1_zpval0.05.db")
  count_matrix<-as.data.frame(matrix(NA,nrow=length(files),ncol=2))
  for (i in 1:length(files)){
    con <- dbConnect(RSQLite::SQLite(), "Z:/data/TOPMED_Proteome/" %&% pop_list[pop] %&% "/PCAIR_modeling/06Elastic_net/dbs_out/" %&% files[i])
    extra<-dbReadTable(con,"extra")
    count_matrix[i,1]<-files[i]
    count_matrix[i,2]<-nrow(extra)
  }
  model_counts_list[[pop]]<-count_matrix
}

```

## make some quick tables for summarization


```{r pressure, echo=FALSE}

model_counts<-bind_rows(model_counts_list) %>%
  mutate(pop=substr(V1,1,3)) %>%
  mutate(axis_labels=if_else(grepl("base",V1),"baseline",str_extract(V1,"0\\.?[01]+_[TF]"))) %>%
  mutate(axis_labels=if_else(is.na(axis_labels),str_extract(V1,"0_[TF]"),axis_labels)) %>% 
  filter(!grepl("PAV",V1)) %>%
  select(-V1)

wide<-pivot_wider(model_counts,id_cols=pop,names_from=axis_labels,values_from=V2)
fwrite(wide,"Z:/scratch/TOPMed_Proteome/06Elastic_net/model_counts/signif_model_counts_unfiltered_for_PAV.txt",col.names=T,row.names=F,sep='\t',quote = F)

model_counts_PAV_filt<-bind_rows(model_counts_list) %>%
  mutate(pop=substr(V1,1,3)) %>%
  mutate(axis_labels=if_else(grepl("base",V1),"baseline",str_extract(V1,"0\\.?[01]+_[TF]"))) %>%
  mutate(axis_labels=if_else(is.na(axis_labels),str_extract(V1,"0_[TF]"),axis_labels)) %>% 
  filter(grepl("PAV",V1)) %>%
  select(-V1)

wide_PAV_filt<-pivot_wider(model_counts_PAV_filt,id_cols=pop,names_from=axis_labels,values_from=V2)
fwrite(wide_PAV_filt,"Z:/scratch/TOPMed_Proteome/06Elastic_net/model_counts/signif_model_counts_filtered_for_PAV.txt",col.names=T,row.names=F,sep='\t',quote = F)
```

## now read in all the data to compare how many unique proteins we get

```{r}

pop_list<-c("CAU","CHN","AFA","HIS","ALL")
model_counts_list<-list(rep(NA,5))
for (pop in 1:length(pop_list)){
  files<-list.files("Z:/data/TOPMED_Proteome/" %&% pop_list[pop] %&% "/PCAIR_modeling/06Elastic_net/dbs_out/",pattern="rho0.1_zpval0.05.db")
  inner_list<-list()
  for (i in 1:length(files)){
    con <- dbConnect(RSQLite::SQLite(), "Z:/data/TOPMED_Proteome/" %&% pop_list[pop] %&% "/PCAIR_modeling/06Elastic_net/dbs_out/" %&% files[i])
    extra<-dbReadTable(con,"extra")
    inner_list[[i]]<-extra %>% select(gene) %>% mutate(model=files[i])
  }
  model_counts_list[[pop]]<-bind_rows(inner_list)
}

total_models<-bind_rows(model_counts_list)
```

```{r}
unique_models<-unique(total_models$gene)
length(unique_models)
```

## quick plots

```{r}
plot_counts<-model_counts %>% separate(axis_labels,into=c("PIP","LD Filtered"),remove=F,sep="_")


ggplot(data=plot_counts[plot_counts$axis_labels != "baseline",]) +
  geom_point(aes(x=PIP,y=V2,colour=`LD Filtered`)) + 
  geom_line(aes(x=PIP,y=V2,colour=`LD Filtered`,group=`LD Filtered`)) +
  facet_wrap(~pop) +
  theme_bw() +
  geom_hline(data=plot_counts[plot_counts$axis_labels == "baseline",],aes(yintercept = V2))
```