---
title: "count how many significant models in topmed"
author: "Ryan Schubert"
date: "December 3, 2020"
output: html_document
---

```{r setup, include=FALSE}
library(RSQLite)
library(tidyr)
library(dplyr)
library(ggplot2)
library(viridis)
"%&%" = function(a,b) paste(a,b,sep="")
```


# get mashr lists

```{r}

mash_dir<-"Z:/scratch/TOPMed_Proteome/06Elastic_net/mashr/eqtl/mashr/"
mash_files<-list.files(mash_dir,"*db")
mash_list<-vector(mode="list",length(mash_files))
for (m in 1:length(mash_files)){
  mashcon<-dbConnect(RSQLite::SQLite(),mash_dir %&% mash_files[m])
  mash_list[[m]]<-dbReadTable(mashcon,"extra") %>% select(gene)
  dbDisconnect(mashcon)
}
mashr_genes<-bind_rows(mash_list) %>% 
  arrange() %>% 
  distinct() %>% 
  mutate(gene=gsub("\\.[0-9]+","",gene)) %>% 
  unlist() %>% 
  unname()

# mashr_genes<-gsub("\\.[0-9]+","",mashr_models$gene)


```

## get model counts for each set

```{r cars}

pop_list<-c("CAU","CHN","AFA","HIS","ALL")
model_counts_list<-list()
for ( pop in 1:length(pop_list)){
  files<-list.files("Z:/data/TOPMED_Proteome/" %&% pop_list[pop] %&% "/PCAIR_modeling/06Elastic_net/dbs_out/",pattern="*rho0.1_zpval0.05.db")
  file_list<-list()
  for ( i in 1: length(files)){
    con <- dbConnect(RSQLite::SQLite(), "Z:/data/TOPMED_Proteome/" %&% pop_list[pop] %&% "/PCAIR_modeling/06Elastic_net/dbs_out/" %&% files[i])
    extra<-dbReadTable(con,"extra") %>% separate(gene,into=c("apt","ENSG"),remove=F) %>%
      mutate(model=files[i],
             ENSG=gsub("\\.[0-9]+","",ENSG),
             in_mashr=if_else(ENSG %in% mashr_genes,TRUE,FALSE))
    file_list[[i]]<-extra
  }
  model_counts_list[[pop]]<-bind_rows(file_list) 
}


```

## Quick summarize

```{r}
unique_genes<-model_counts_df$gene %>% unique
unique_proteins<-model_counts_df$genename %>% unique
table(model_counts_df$model)
```


## make some quick tables for summarization


```{r pressure, echo=FALSE}
model_counts_df<-bind_rows(model_counts_list) %>%
  mutate(train_pop=substr(model,1,3),
         train_pop=if_else(train_pop=="CAU","EUR",train_pop),
         PAV_filtered=if_else(grepl("PAV_filtered",model),TRUE,FALSE),
         model=gsub("_rho0\\.1_zpval0\\.05\\.db","",model),
         model=gsub("_PAV_filtered","",model),
         model=gsub("_models","",model),
         model=gsub("dapg_","",model),
         model=gsub("[A-Z]+_PCAIR_","",model))

ggplot(data=model_counts_df) +
  geom_bar(aes(x=model,fill=in_mashr))

model_counts_df %>%
  filter(model %in% c("baseline","0.001_T"),PAV_filtered==FALSE) %>%
  mutate(model=if_else(model=="0.001_T","Fine-mapped",model)) %>%
  ggplot(data=.) +
  geom_bar(aes(x=model,fill=train_pop),position = position_dodge()) +
  theme_bw() +
  scale_fill_viridis(discrete=T) +
  labs(fill="Training\nPopulation") +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/model_counts.pdf",dpi=700) +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/model_counts.tiff",dpi=700) +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/model_counts.png",dpi=700)

model_counts_df %>%
  filter(model %in% c("baseline","0.001_T"),PAV_filtered==TRUE) %>%
  mutate(model=if_else(model=="0.001_T","Fine-mapped",model)) %>%
  ggplot(data=.) +
  geom_bar(aes(x=model,fill=train_pop),position = position_dodge()) +
  theme_bw() +
  scale_fill_viridis(discrete=T) +
  labs(fill="Training\nPopulation") +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/model_counts_PAV_filtered.pdf",dpi=700) +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/model_counts_PAV_filtered.tiff",dpi=700) +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/model_counts_PAV_filtered.png",dpi=700)

model_counts_df %>%
  filter(PAV_filtered==FALSE) %>%
  mutate(model=factor(model, levels=c("0_F", "0_T", "0.001_F","0.001_T","0.01_F","0.01_T","baseline"))) %>%
  ggplot(data=.) +
  geom_bar(aes(x=model,fill=train_pop),position = position_dodge()) +
  theme_bw() +
  scale_fill_viridis(discrete=T) +
  labs(fill="Training\nPopulation") +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/supplemental_model_counts.pdf",dpi=700) +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/supplemental_model_counts.tiff",dpi=700) +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/supplemental_model_counts.png",dpi=700)

model_counts_df %>%
  filter(PAV_filtered==TRUE) %>%
  mutate(model=factor(model, levels=c("0_F", "0_T", "0.001_F","0.001_T","0.01_F","0.01_T","baseline"))) %>%
  ggplot(data=.) +
  geom_bar(aes(x=model,fill=train_pop),position = position_dodge()) + 
  theme_bw() +
  scale_fill_viridis(discrete=T) +
  labs(fill="Training\nPopulation") +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/supplemental_model_counts_PAV_filtered.pdf",dpi=700) +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/supplemental_model_counts_PAV_filtered.tiff",dpi=700) +
  ggsave("Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/supplemental_model_counts_PAV_filtered.png",dpi=700)



```

# get some exact numbers

```{r}
unique(model_counts_df$apt) %>% length()

model_counts_df %>% count(model,PAV_filtered,train_pop)

not_in_mashr<-model_counts_df %>% 
  filter(in_mashr==FALSE)  %>%
  select(apt,ENSG,pred.perf.R2,pred.perf.pval,model,PAV_filtered,train_pop)
fwrite(not_in_mashr,"Z:/scratch/TOPMed_Proteome/figures_and_tables/final_figures_and_tables/figures_and_tables/comprehensive_not_in_mashr_summaries.csv")

```
